### ISSUE TITLE
zsh: exec format error: trustcache when trying to use trustcache info

### ISSUE THREAD

**Issue by alfiecg24** [CRKatri/trustcache#2]
If I run the program on any trustcache with the info option, I get an exec format error. I have tried using even the trust caches used in the IPSWs but I get the same error.

**Comment by alfiecg24** [comment]
I get the same error when I use trustcache create too

**Comment by CRKatri** [comment]
That is because the executable you created is for the wrong platform. What OS did you compile it on, and what OS are you trying to run it on?

**Comment by alfiecg24** [comment]
I thought that, but I’m on an M1 Mac and just ran `make` and tried to execute it on the same machine.

**Comment by CRKatri** [comment]
Run `file trustcache` and `vtool -show trustcache`

**Comment by alfiecg24** [comment]
I ended up running `make clean` and then `make trustcache` and the executable now works - but I am running into malloc errors so I'll try and debug when I get round to it
